name: Build OrangeFox

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Free Disk Space
      run: |
        sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc
        sudo apt update
        sudo apt install -y build-essential gcc-multilib ccache imagemagick libx11-dev git repo

    - name: Setup Environment and Repo
      run: |
        mkdir -p ~/bin
        curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
        chmod a+x ~/bin/repo
        echo "$HOME/bin" >> $GITHUB_PATH

    - name: Initialize and Sync OrangeFox Source
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        mkdir -p ~/fox
        cd ~/fox
        repo init -u https://gitlab.com/OrangeFox/Building/manifest.git -b fox_12.1 --depth=1
        repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune -j$(nproc --all)
